### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by adamc199** [dtcooper/raspotify#118]
I double and triple checked I entered the correct credentials in /etc/default/librespot but I keep getting a panic on "Bad Credentials"

`May 22 15:27:18 nuts librespot[4787]: INFO:librespot: librespot (raspotify) 6edcef0 (2018-05-17). Built on 2018-05-17. Build ID: WQ2iGeSh
May 22 15:27:18 nuts librespot[4787]: INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-b-htm4.ap.spotify.com:4070"
May 22 15:27:19 nuts librespot[4787]: thread 'main' panicked at 'Authentication failed with reason: BadCredentials', core/src/connection/mod.rs:93:21
May 22 15:27:19 nuts librespot[4787]: stack backtrace:
May 22 15:27:19 nuts librespot[4787]:    0:   0x98ac9b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd7ee9e6e2fbd0546
May 22 15:27:19 nuts librespot[4787]:                        at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
May 22 15:27:19 nuts librespot[4787]:    1:   0x991ce3 - std::sys_common::backtrace::print::ha543f35261e05af8
May 22 15:27:19 nuts librespot[4787]:                        at libstd/sys_common/backtrace.rs:71
May 22 15:27:19 nuts librespot[4787]:                        at libstd/sys_common/backtrace.rs:59
May 22 15:27:19 nuts librespot[4787]:    2:   0x9812a3 - std::panicking::default_hook::{{closure}}::h4e2726d8115dc6e7
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:207
May 22 15:27:19 nuts librespot[4787]:    3:   0x980ef7 - std::panicking::default_hook::heb92eb7475fdb71c
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:223
May 22 15:27:19 nuts librespot[4787]:    4:   0x98174b - std::panicking::rust_panic_with_hook::hdc6f326636ed669e
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:402
May 22 15:27:19 nuts librespot[4787]:    5:   0x981567 - std::panicking::begin_panic_fmt::hc0834ed5723739e8
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:349
May 22 15:27:19 nuts librespot[4787]:    6:   0x5f9d5b - <futures::future::chain::Chain<A, B, C>>::poll::h1148c6132503b5cf
May 22 15:27:19 nuts librespot[4787]:    7:   0x61c5b7 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h1cce02c614c2a85c
May 22 15:27:19 nuts librespot[4787]:    8:   0x604e1f - <futures::future::chain::Chain<A, B, C>>::poll::h86ae1f1e239d835f
May 22 15:27:19 nuts librespot[4787]:    9:   0x65000b - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h961e6c3a5beec363
May 22 15:27:19 nuts librespot[4787]:   10:   0x4ca1bf - <librespot::Main as futures::future::Future>::poll::hc5558f1fdc6e23ed
May 22 15:27:19 nuts librespot[4787]:   11:   0x4a395f - <futures::task_impl::Spawn<T>>::poll_future_notify::hc9211ab06780cae1
May 22 15:27:19 nuts librespot[4787]:   12:   0x4a375f - <futures::task_impl::Spawn<T>>::poll_future_notify::ha8b42b6b522978eb
May 22 15:27:19 nuts librespot[4787]:   13:   0x4ad74f - <std::thread::local::LocalKey<T>>::with::h2c21813f4460189b
May 22 15:27:19 nuts librespot[4787]:   14:   0x4ba22f - <tokio::executor::current_thread::Entered<'a, P>>::block_on::hf43c8a2fdba49de7
May 22 15:27:19 nuts librespot[4787]:   15:   0x4ad947 - <std::thread::local::LocalKey<T>>::with::h76146f30987650d4
May 22 15:27:19 nuts librespot[4787]:   16:   0x4add6b - <std::thread::local::LocalKey<T>>::with::hd6791b0e6c65e9d1
May 22 15:27:19 nuts librespot[4787]:   17:   0x4ad617 - <std::thread::local::LocalKey<T>>::with::h2a5318e41afac7f6
May 22 15:27:19 nuts librespot[4787]:   18:   0x4a980b - tokio_core::reactor::Core::run::ha49f6d3f8aa188c1
May 22 15:27:19 nuts librespot[4787]:   19:   0x4cc7f3 - librespot::main::h54f3befa380b485c
May 22 15:27:19 nuts librespot[4787]:   20:   0x4bfce3 - std::rt::lang_start::{{closure}}::h71794c74d2130e37
May 22 15:27:19 nuts librespot[4787]:   21:   0x9813f7 - std::panicking::try::do_call::h5731926498d75d4e
May 22 15:27:19 nuts librespot[4787]:                        at libstd/rt.rs:59
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:306
May 22 15:27:19 nuts librespot[4787]:   22:   0x9988c3 - __rust_maybe_catch_panic
May 22 15:27:19 nuts librespot[4787]:                        at libpanic_unwind/lib.rs:102
May 22 15:27:19 nuts librespot[4787]:   23:   0x97e88f - std::rt::lang_start_internal::h011c0cae803bbfbf
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panicking.rs:285
May 22 15:27:19 nuts librespot[4787]:                        at libstd/panic.rs:361
May 22 15:27:19 nuts librespot[4787]:                        at libstd/rt.rs:58
May 22 15:27:19 nuts librespot[4787]:   24:   0x4cd243 - main
May 22 15:27:19 nuts librespot[4787]:   25: 0x76ca3677 - __libc_start_main
`

**Comment by adamc199** [comment]
Upon further review:

I had replaced <USERNAME> with my username in <> brackets. I did not realize I needed to replace the entire string including the brackets. 

Same for <PASSWORD>
