### ISSUE TITLE
spotify connect permission error ?

### ISSUE THREAD

**Issue by spippoli** [dtcooper/raspotify#371]
Hi, 
I installed raspotify on my Raspberry pi zero alon with pi-btaudio to stream music to my bluetooth speaker. Bluetooth connection is working but as soon as I try to connect spotify to raspotify I get the error below, which suggests an issue with permissions but everything I checked seems fine.

```
Mar  2 23:35:05 spodisplay librespot[991]: [2021-03-02T19:35:05Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-e-bgsc.ap.spotify.com:4070"
Mar  2 23:35:05 spodisplay librespot[991]: [2021-03-02T19:35:05Z INFO  librespot_core::session] Authenticated as "[REDACTED]" !
Mar  2 23:35:05 spodisplay librespot[991]: [2021-03-02T19:35:05Z INFO  librespot_core::session] Country: "IT"
Mar  2 23:35:05 spodisplay librespot[991]: [2021-03-02T19:35:05Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
Mar  2 23:35:05 spodisplay librespot[991]: [2021-03-02T19:35:05Z INFO  librespot::player_event_handler] Running ["/opt/raspodisplay/run_client.sh"] with environment variables {"VOLUME": "65535", "PLAYER_EVENT": "volume_set"}
Mar  2 23:35:05 spodisplay librespot[991]: thread 'main' panicked at 'program failed to start: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:577:34
Mar  2 23:35:05 spodisplay librespot[991]: stack backtrace:
Mar  2 23:35:05 spodisplay librespot[991]:    0:   0x962278 - std::backtrace_rs::backtrace::libunwind::trace::h9c6af82ecb947420
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
Mar  2 23:35:05 spodisplay librespot[991]:    1:   0x962278 - std::backtrace_rs::backtrace::trace_unsynchronized::h80561bf66e637b12
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
Mar  2 23:35:05 spodisplay librespot[991]:    2:   0x962278 - std::sys_common::backtrace::_print_fmt::h8904fddc87bf6b5e
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
Mar  2 23:35:05 spodisplay librespot[991]:    3:   0x962278 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc883ceb7a13219f2
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
Mar  2 23:35:05 spodisplay librespot[991]:    4:   0x98a290 - core::fmt::write::ha75209c8e86bef45
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
Mar  2 23:35:05 spodisplay librespot[991]:    5:   0x95ae18 - std::io::Write::write_fmt::h4cce8be81a41c537
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
Mar  2 23:35:05 spodisplay librespot[991]:    6:   0x9651c0 - std::sys_common::backtrace::_print::hdc9e28891c09ab0b
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
Mar  2 23:35:05 spodisplay librespot[991]:    7:   0x9651c0 - std::sys_common::backtrace::print::h85895381379b4dc1
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
Mar  2 23:35:05 spodisplay librespot[991]:    8:   0x9651c0 - std::panicking::default_hook::{{closure}}::h6b4de484f2428118
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
Mar  2 23:35:05 spodisplay librespot[991]:    9:   0x964dbc - std::panicking::default_hook::h3966366a200b03f1
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
Mar  2 23:35:05 spodisplay librespot[991]:   10:   0x965910 - std::panicking::rust_panic_with_hook::h068b5368b0949ced
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
Mar  2 23:35:05 spodisplay librespot[991]:   11:   0x9654c4 - std::panicking::begin_panic_handler::{{closure}}::hde463ebfc6f96538
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
Mar  2 23:35:05 spodisplay librespot[991]:   12:   0x9627f8 - std::sys_common::backtrace::__rust_end_short_backtrace::hb945924c40726c97
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
Mar  2 23:35:05 spodisplay librespot[991]:   13:   0x96547c - rust_begin_unwind
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
Mar  2 23:35:05 spodisplay librespot[991]:   14:   0x987960 - core::panicking::panic_fmt::h27b19d6e6dedd33e
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
Mar  2 23:35:05 spodisplay librespot[991]:   15:   0x9877b8 - core::option::expect_none_failed::h0ec77a052e666b69
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
Mar  2 23:35:05 spodisplay librespot[991]:   16:   0x53c120 - <librespot::Main as futures::future::Future>::poll::h169a5d4027f550f1
Mar  2 23:35:05 spodisplay librespot[991]:   17:   0x52ecf0 - futures::task_impl::std::set::h171bb0e3315231c5
Mar  2 23:35:05 spodisplay librespot[991]:   18:   0x54d5b0 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h6ad5d06c62a954b1
Mar  2 23:35:05 spodisplay librespot[991]:   19:   0x52ee70 - futures::task_impl::std::set::h1b4107da043418f3
Mar  2 23:35:05 spodisplay librespot[991]:   20:   0x525c1c - std::thread::local::LocalKey<T>::with::h10f666118935c490
Mar  2 23:35:05 spodisplay librespot[991]:   21:   0x5246b8 - tokio_current_thread::Entered<P>::block_on::hbb47725fa57f8e44
Mar  2 23:35:05 spodisplay librespot[991]:   22:   0x52b5b8 - tokio_timer::timer::handle::with_default::h938751ab893a9316
Mar  2 23:35:05 spodisplay librespot[991]:   23:   0x525ff8 - std::thread::local::LocalKey<T>::with::hed23bc0e3035947a
Mar  2 23:35:05 spodisplay librespot[991]:   24:   0x523990 - scoped_tls::ScopedKey<T>::set::heda756cd7e82ddd6
Mar  2 23:35:05 spodisplay librespot[991]:   25:   0x52acf0 - tokio_core::reactor::Core::run::hccb77cd75ccb2c67
Mar  2 23:35:05 spodisplay librespot[991]:   26:   0x53e448 - librespot::main::h6da7c78e457a1f2f
Mar  2 23:35:05 spodisplay librespot[991]:   27:   0x525abc - std::sys_common::backtrace::__rust_begin_short_backtrace::h92f05e3879870930
Mar  2 23:35:05 spodisplay librespot[991]:   28:   0x54830c - std::rt::lang_start::{{closure}}::h067bf4c6ab425fd6
Mar  2 23:35:05 spodisplay librespot[991]:   29:   0x965d30 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2c136973bfb85920
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
Mar  2 23:35:05 spodisplay librespot[991]:   30:   0x965d30 - std::panicking::try::do_call::hc0787118c306af2e
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
Mar  2 23:35:05 spodisplay librespot[991]:   31:   0x965d30 - std::panicking::try::he0aeb9ab5f254114
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
Mar  2 23:35:05 spodisplay librespot[991]:   32:   0x965d30 - std::panic::catch_unwind::hb91533e13ff48846
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
Mar  2 23:35:05 spodisplay librespot[991]:   33:   0x965d30 - std::rt::lang_start_internal::hf9465186f7b70c75
Mar  2 23:35:05 spodisplay librespot[991]:                        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
Mar  2 23:35:05 spodisplay librespot[991]:   34:   0x53f460 - main
Mar  2 23:35:05 spodisplay librespot[991]:   35: 0xb6cb7718 - __libc_start_main
Mar  2 23:35:05 spodisplay systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a


```

**Comment by spippoli** [comment]
closed this as I found the problem was the on events script missing the execution bit
