### ISSUE TITLE
Crash when play

### ISSUE THREAD

**Issue by Nuke142** [dtcooper/raspotify#400]
Just bought Pi Zero W and installed RaspiOS Lite from here https://www.raspberrypi.org/software/operating-systems/light 
After that installed raspotify.
What am I doing wrong? Service crashed when i push play after choosing raspberry in spotify connect.

```
pi@raspberrypi:~ $ /usr/bin/librespot --name rasp --device-type speaker --backend alsa --bitrate 320 --disable-audio-cache --volume-ctrl linear --initial-volume 50 -v
[2021-06-03T13:12:04Z INFO  librespot] librespot (raspotify v0.16.0) 0adb851 (2020-12-15). Built on 2020-12-30. Build ID: KLdkAvgt
[2021-06-03T13:12:04Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:35539
[2021-06-03T13:12:10Z DEBUG librespot_connect::discovery] Post "/" {}
[2021-06-03T13:12:10Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-d-h8zm.ap.spotify.com:4070"
[2021-06-03T13:12:11Z INFO  librespot_core::session] Authenticated as "z3efh6a1zvkdn7g3dvh5ngtno" !
[2021-06-03T13:12:11Z DEBUG librespot_core::session] new Session[0]
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] new Spirc[0]
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] canonical_username: z3efh6a1zvkdn7g3dvh5ngtno
[2021-06-03T13:12:11Z DEBUG librespot_core::mercury] new MercuryManager
[2021-06-03T13:12:11Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
[2021-06-03T13:12:11Z INFO  librespot_core::session] Country: "RU"
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] new Player[0]
[2021-06-03T13:12:11Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] command=AddEventSender
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] command=VolumeSet(32767)
[2021-06-03T13:12:11Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/z3efh6a1zvkdn7g3dvh5ngtno/ count=0
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Android" c4655f56da2062cc47b0146a7a4a42a97d2709df 1375777725 1622725931210 kPlayStatusStop
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] kMessageTypeLoad "Android" c4655f56da2062cc47b0146a7a4a42a97d2709df 1375778202 1622725931210 kPlayStatusPause
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:search:prodigy" index: 0 position_ms: 5022 status: kPlayStatusPause position_measured_at: 1622725931714 context_description: "" shuffle: false repeafalse playing_from_fallback: true row: 0 playing_track_index: 0 track {gid: "#\003\"\367\206\366BI\276\231\205\212\341\014\323\333"}
[2021-06-03T13:12:11Z DEBUG librespot_connect::spirc] Frame has 1 tracks
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 46539265956099025318824418544349664219, audio_type: Track }, false, 5022)
[2021-06-03T13:12:11Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPause]
[2021-06-03T13:12:11Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPause]
[2021-06-03T13:12:11Z INFO  librespot_playback::player] Loading <Omen> with Spotify URI <spotify:track:144adL7pGHEWRwute2wxzZ>
[2021-06-03T13:12:11Z DEBUG librespot_core::audio_key] new AudioKeyManager
[2021-06-03T13:12:11Z DEBUG librespot_audio::fetch] Downloading file 1489a0c3892a6b6a7b7bb7e7586b736dff12613d
[2021-06-03T13:12:11Z DEBUG librespot_core::channel] new ChannelManager
[2021-06-03T13:12:11Z TRACE librespot_audio::fetch] Ping time estimated as: 92 ms.
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: -9.360001, track_peak: 1.023786, album_gain_db: -9.690002, album_peak: 1.0713903 }
[2021-06-03T13:12:11Z DEBUG librespot_playback::player] Applied normalisation factor: 0.34040818
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 72 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 67 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 68 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 64 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 67 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 64 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 68 ms.
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 65 ms.
[2021-06-03T13:12:12Z INFO  librespot_playback::player] <Omen> (216026 ms) loaded
[2021-06-03T13:12:12Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPause]
[2021-06-03T13:12:12Z TRACE librespot_connect::spirc] ==> kPlayStatusPause
[2021-06-03T13:12:12Z TRACE librespot_audio::fetch] Ping time estimated as: 75 ms.
[2021-06-03T13:12:16Z DEBUG librespot_connect::spirc] kMessageTypePlay "Android" c4655f56da2062cc47b0146a7a4a42a97d2709df 1375782947 1622725933013 kPlayStatusPause
[2021-06-03T13:12:16Z DEBUG librespot_playback::player] command=Play
[2021-06-03T13:12:16Z TRACE librespot_playback::player] == Starting sink ==
[2021-06-03T13:12:16Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2021-06-03T13:12:16Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
[2021-06-03T13:12:16Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[2021-06-03T13:12:16Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
[2021-06-03T13:12:16Z TRACE librespot_playback::player] == Starting sink ==
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
[2021-06-03T13:12:16Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[2021-06-03T13:12:16Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
[2021-06-03T13:12:16Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2021-06-03T13:12:16Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
[2021-06-03T13:12:16Z TRACE librespot_playback::player] == Starting sink ==
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
[2021-06-03T13:12:16Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[2021-06-03T13:12:16Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', playback/src/audio_backend/alsa.rs:138:45
stack backtrace:
   0:   0x89a278 - std::backtrace_rs::backtrace::libunwind::trace::h9c6af82ecb947420
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:   0x89a278 - std::backtrace_rs::backtrace::trace_unsynchronized::h80561bf66e637b12
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:   0x89a278 - std::sys_common::backtrace::_print_fmt::h8904fddc87bf6b5e
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:   0x89a278 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc883ceb7a13219f2
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:   0x8c2290 - core::fmt::write::ha75209c8e86bef45
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:   0x892e18 - std::io::Write::write_fmt::h4cce8be81a41c537
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:   0x89d1c0 - std::sys_common::backtrace::_print::hdc9e28891c09ab0b
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:   0x89d1c0 - std::sys_common::backtrace::print::h85895381379b4dc1
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:   0x89d1c0 - std::panicking::default_hook::{{closure}}::h6b4de484f2428118
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:   0x89cdbc - std::panicking::default_hook::h3966366a200b03f1
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:   0x89d910 - std::panicking::rust_panic_with_hook::h068b5368b0949ced
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:   0x89d4c4 - std::panicking::begin_panic_handler::{{closure}}::hde463ebfc6f96538
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:   0x89a7f8 - std::sys_common::backtrace::__rust_end_short_backtrace::hb945924c40726c97
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:   0x89d47c - rust_begin_unwind
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:   0x8bf960 - core::panicking::panic_fmt::h27b19d6e6dedd33e
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:   0x8bf8bc - core::panicking::panic::h2a6f9b05d102de10
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:   0x526020 - <librespot_playback::audio_backend::alsa::AlsaSink as librespot_playback::audio_backend::Sink>::write::hfb124b87fed1cc15
  17:   0x503304 - <librespot_playback::player::PlayerInternal as futures::future::Future>::poll::he6e04a5bccf94e34
  18:   0x467300 - futures::task_impl::std::set::hab1c1811473e3998
  19:   0x45d838 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8286c5a0fd04a387
  20:   0x4784f4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h76e6c7604d7daced
  21:   0x8a4940 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6b7ad05f87ff90ae
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  22:   0x8a4940 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he9130e675b8d97ee
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  23:   0x8a4940 - std::sys::unix::thread::Thread::new::thread_start::h7a3f6590d8e03e95
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
[2021-06-03T13:12:16Z DEBUG librespot_playback::player] drop PlayerInternal[0]
[2021-06-03T13:12:18Z DEBUG librespot_connect::spirc] kMessageTypePause "Android" c4655f56da2062cc47b0146a7a4a42a97d2709df 1375784693 1622725936699 kPlayStatusPlay
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', playback/src/player.rs:281:61
stack backtrace:
   0:   0x89a278 - std::backtrace_rs::backtrace::libunwind::trace::h9c6af82ecb947420
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:   0x89a278 - std::backtrace_rs::backtrace::trace_unsynchronized::h80561bf66e637b12
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:   0x89a278 - std::sys_common::backtrace::_print_fmt::h8904fddc87bf6b5e
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:   0x89a278 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc883ceb7a13219f2
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:   0x8c2290 - core::fmt::write::ha75209c8e86bef45
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:   0x892e18 - std::io::Write::write_fmt::h4cce8be81a41c537
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:   0x89d1c0 - std::sys_common::backtrace::_print::hdc9e28891c09ab0b
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:   0x89d1c0 - std::sys_common::backtrace::print::h85895381379b4dc1
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:   0x89d1c0 - std::panicking::default_hook::{{closure}}::h6b4de484f2428118
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:   0x89cdbc - std::panicking::default_hook::h3966366a200b03f1
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:   0x89d910 - std::panicking::rust_panic_with_hook::h068b5368b0949ced
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:   0x89d4c4 - std::panicking::begin_panic_handler::{{closure}}::hde463ebfc6f96538
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:   0x89a7f8 - std::sys_common::backtrace::__rust_end_short_backtrace::hb945924c40726c97
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:   0x89d47c - rust_begin_unwind
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:   0x8bf960 - core::panicking::panic_fmt::h27b19d6e6dedd33e
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:   0x8bf7b8 - core::option::expect_none_failed::h0ec77a052e666b69
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:   0x5000a8 - librespot_playback::player::Player::pause::h4bd7037998ab1226
  17:   0x4af590 - librespot_connect::spirc::SpircTask::handle_pause::had01063f6bb2c635
  18:   0x4ada34 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h400d0c6a9af9b895
  19:   0x473ab4 - <librespot::Main as futures::future::Future>::poll::h169a5d4027f550f1
  20:   0x466cf0 - futures::task_impl::std::set::h171bb0e3315231c5
  21:   0x4855b0 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h6ad5d06c62a954b1
  22:   0x466e70 - futures::task_impl::std::set::h1b4107da043418f3
  23:   0x45dc1c - std::thread::local::LocalKey<T>::with::h10f666118935c490
  24:   0x45c6b8 - tokio_current_thread::Entered<P>::block_on::hbb47725fa57f8e44
  25:   0x4635b8 - tokio_timer::timer::handle::with_default::h938751ab893a9316
  26:   0x45dff8 - std::thread::local::LocalKey<T>::with::hed23bc0e3035947a
  27:   0x45b990 - scoped_tls::ScopedKey<T>::set::heda756cd7e82ddd6
  28:   0x462cf0 - tokio_core::reactor::Core::run::hccb77cd75ccb2c67
  29:   0x476448 - librespot::main::h6da7c78e457a1f2f
  30:   0x45dabc - std::sys_common::backtrace::__rust_begin_short_backtrace::h92f05e3879870930
  31:   0x48030c - std::rt::lang_start::{{closure}}::h067bf4c6ab425fd6
  32:   0x89dd30 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2c136973bfb85920
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  33:   0x89dd30 - std::panicking::try::do_call::hc0787118c306af2e
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  34:   0x89dd30 - std::panicking::try::he0aeb9ab5f254114
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  35:   0x89dd30 - std::panic::catch_unwind::hb91533e13ff48846
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  36:   0x89dd30 - std::rt::lang_start_internal::hf9465186f7b70c75
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  37:   0x477460 - main
  38: 0xb6c8c718 - __libc_start_main
[2021-06-03T13:12:18Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2021-06-03T13:12:18Z DEBUG librespot_playback::player] Shutting down player thread ...
[2021-06-03T13:12:18Z ERROR librespot_playback::player] Player thread panicked!
[2021-06-03T13:12:18Z DEBUG librespot_core::session] drop Session[0]
[2021-06-03T13:12:18Z DEBUG librespot_core::audio_key] drop AudioKeyManager
[2021-06-03T13:12:18Z DEBUG librespot_core::channel] drop ChannelManager
[2021-06-03T13:12:18Z DEBUG librespot_core::mercury] drop MercuryManager
[2021-06-03T13:12:18Z DEBUG librespot_core::session] drop Dispatch
pi@raspberrypi:~ $

```

**Comment by Nuke142** [comment]
Fixed with https://github.com/dtcooper/raspotify/issues/235#issuecomment-772794436
--device plughw:1,0
insted of --device hw:1,0
