### ISSUE TITLE
Versions 0.3xx do not work

### ISSUE THREAD

**Issue by avizero** [dtcooper/raspotify#463]
Hi!

```
avi@cubietruck:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"

avi@cubietruck:~$ uname -a
Linux cubietruck 3.4.113-sun7i #127 SMP PREEMPT Sat May 4 08:38:36 CEST 2019 armv7l armv7l armv7l GNU/Linux
```
Unfortunately I cannot change the system due to driver problems.

In newer versions librespot fails with the following error:
```
avi@cubietruck:~$ librespot
[2021-11-27T06:58:49Z INFO  librespot] librespot 0.3.1 bbd575e (Built on 2021-11-26, Build ID: a6e0Ery3, Profile: release)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DnsSdError(Os { code: 92, kind: Uncategorized, message: "Protocol not available" })', src/main.rs:1453:18
stack backtrace:
   0: 0xb6e07388 - std::backtrace_rs::backtrace::libunwind::trace::h4bf3e5497ce7d0d1
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1: 0xb6e07388 - std::backtrace_rs::backtrace::trace_unsynchronized::h6b664ef1002045f8
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0xb6e07388 - std::sys_common::backtrace::_print_fmt::h077a74dd0fd95079
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3: 0xb6e07388 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha65a6b17248d4482
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4: 0xb6e306b0 - core::fmt::write::h682b611af217d220
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5: 0xb6dfff74 - std::io::Write::write_fmt::h8cc061d257db1323
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6: 0xb6e094a4 - std::sys_common::backtrace::_print::h8ea36d0a4c8c8101
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7: 0xb6e094a4 - std::sys_common::backtrace::print::h27c30ada45da6e69
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8: 0xb6e094a4 - std::panicking::default_hook::{{closure}}::h2ac34510ecc99ccd
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9: 0xb6e08f00 - std::panicking::default_hook::ha1d2ed057431f9b0
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10: 0xb6e09b7c - std::panicking::rust_panic_with_hook::h17c1e02f294ac808
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11: 0xb6e09658 - std::panicking::begin_panic_handler::{{closure}}::h9573bd22277952be
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12: 0xb6e07910 - std::sys_common::backtrace::__rust_end_short_backtrace::h99bf7f87f84ce00f
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13: 0xb6e095b0 - rust_begin_unwind
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14: 0xb69aac40 - core::panicking::panic_fmt::h9bf8e44e3548ebaf
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15: 0xb69aad14 - core::result::unwrap_failed::hd4e3cc68582ec94f
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  16: 0xb6a25750 - librespot::main::{{closure}}::h217d0993b7abbf65
  17: 0xb69fa554 - tokio::macros::scoped_tls::ScopedKey<T>::set::hcc50d82800b42cb0
  18: 0xb6a638c0 - tokio::runtime::Runtime::block_on::hd0bc65a4e3a84030
  19: 0xb69e0848 - librespot::main::hab7e1d970e7ec756
  20: 0xb6a59fa8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h600bebf43c02572f
  21: 0xb6a50828 - std::rt::lang_start::{{closure}}::h93555ac7810af506
  22: 0xb6e0a1a8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7ba1bdda2f342471
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  23: 0xb6e0a1a8 - std::panicking::try::do_call::h4c3c648f73078093
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  24: 0xb6e0a1a8 - std::panicking::try::h06ab9d03dd62fbbd
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  25: 0xb6e0a1a8 - std::panic::catch_unwind::h82421e9e18ace5da
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  26: 0xb6e0a1a8 - std::rt::lang_start_internal::{{closure}}::h1cbfee7e0ebe057d
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  27: 0xb6e0a1a8 - std::panicking::try::do_call::he9d4b690fd004a7c
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  28: 0xb6e0a1a8 - std::panicking::try::hbd6ed135d4dc763a
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  29: 0xb6e0a1a8 - std::panic::catch_unwind::h45dacf89f176e04b
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  30: 0xb6e0a1a8 - std::rt::lang_start_internal::hd4ee3abcdb019f91
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  31: 0xb69e0930 - main
  32: 0xb66a78aa - __libc_start_main
```

In version 0.16 all  ok

**Comment by JasonLG1979** [comment]
That is a discovery (zeroconf, mDNS) error. Specifically a libmdns error that's happening [right here in the librespot code base](https://github.com/librespot-org/librespot/blob/dev/discovery/src/lib.rs#L118).

I do not know what is causing the error but needless to say that **[Ubuntu 16.04 is not supported at all](https://github.com/dtcooper/raspotify#bug-reports-and-feature-requests)**. You could try disabling discovery and entering your username and password but that would effectually make your Raspotify instance single user since no other account would be able to see it. You also need to enable caching if you do that to save the auth token so you don't have to get a new one every time Raspotify starts. (Spotify will send you a nag email every time telling you a new device has connected if you don'r enable caching) the args you want are `--disable-discovery`, `--username`, `--password`, and `--disable-audio-cache`. You can see the [Raspotify](https://github.com/dtcooper/raspotify/wiki) and [librespot](https://github.com/librespot-org/librespot/wiki) wiki's for further reading.

The easier option to just install [0.16.0](https://github.com/dtcooper/raspotify/releases/tag/0.16.0) and stay with that version until it stops working and don't enable the repo so it doesn't try to update.

In any event I'm closing this, because as I mentioned above **[Ubuntu 16.04 is not supported at all](https://github.com/dtcooper/raspotify#bug-reports-and-feature-requests)**. That's all the advice I can and will offer. From here on your on your own.
