### ISSUE TITLE
Raspotify / librespot crashes/panics when I try to connect and play music

### ISSUE THREAD

**Issue by kirenida** [dtcooper/raspotify#542]
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Latest Version

- [X] I'm running the latest version of Raspotify

### Due Diligence

- [X] I have done my due diligence

### What happened?

Raspotify / librespot gives out errors when I try to connect to it to play anything.
It skips to the next song until I pause playback, and then panics.

Restarting the raspotify service or rebooting the raspberry doesn't help. My partner says it worked a few hours ago.

journalctl output pasted below.

### Relevant log output

```shell
May 05 16:24:26 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
May 05 16:24:26 raspberrypi librespot[2360]: [2022-05-05T14:24:26Z WARN  libmdns] Failed to register IPv6 receiver: Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" }
May 05 16:24:54 raspberrypi librespot[2360]: [2022-05-05T14:24:54Z ERROR librespot_core::channel] channel error: 2 1
May 05 16:24:54 raspberrypi librespot[2360]: [2022-05-05T14:24:54Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
May 05 16:24:54 raspberrypi librespot[2360]: [2022-05-05T14:24:54Z WARN  librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 334968983708361121809017565778119380289, audio_type: Track }>: ()


....more of the same errors...

May 05 16:25:02 raspberrypi librespot[2360]: thread '<unnamed>' panicked at 'Map must not be polled after it returned `Poll::Ready`', /build/cache/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/future/future/map.rs:62:17
May 05 16:25:02 raspberrypi librespot[2360]: stack backtrace:
May 05 16:25:02 raspberrypi librespot[2360]:    0:   0x95b238 - std::backtrace_rs::backtrace::libunwind::trace::h40a4eff66330a36d
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
May 05 16:25:02 raspberrypi librespot[2360]:    1:   0x95b238 - std::backtrace_rs::backtrace::trace_unsynchronized::hbce01963451b0cd5
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
May 05 16:25:02 raspberrypi librespot[2360]:    2:   0x95b238 - std::sys_common::backtrace::_print_fmt::h95da650d09c7e00b
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
May 05 16:25:02 raspberrypi librespot[2360]:    3:   0x95b238 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33b23b1d14f668ff
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
May 05 16:25:02 raspberrypi librespot[2360]:    4:   0x986ffc - core::fmt::write::h6320fb0e6ac90e58
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
May 05 16:25:02 raspberrypi librespot[2360]:    5:   0x953408 - std::io::Write::write_fmt::h33b25d4810ca481f
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
May 05 16:25:02 raspberrypi librespot[2360]:    6:   0x95de58 - std::sys_common::backtrace::_print::h7e61c5be69c715ef
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
May 05 16:25:02 raspberrypi librespot[2360]:    7:   0x95de58 - std::sys_common::backtrace::print::h3cee176d7c8dab8b
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
May 05 16:25:02 raspberrypi librespot[2360]:    8:   0x95de58 - std::panicking::default_hook::{{closure}}::h2d0211dd2e97dc43
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
May 05 16:25:02 raspberrypi librespot[2360]:    9:   0x95da78 - std::panicking::default_hook::hcbdb3b7c40dca30c
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
May 05 16:25:02 raspberrypi librespot[2360]:   10:   0x95e5f8 - std::panicking::rust_panic_with_hook::h4ce49e7a343dc12b
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
May 05 16:25:02 raspberrypi librespot[2360]:   11:   0x66e990 - std::panicking::begin_panic::{{closure}}::hddb55e8494899616
May 05 16:25:02 raspberrypi librespot[2360]:   12:   0x66e728 - std::sys_common::backtrace::__rust_end_short_backtrace::h2a044e2061f17826
May 05 16:25:02 raspberrypi librespot[2360]:   13:   0x4ff880 - std::panicking::begin_panic::h7bddeb53070d044d
May 05 16:25:02 raspberrypi librespot[2360]:   14:   0x684d6c - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h6ca845d4d142d262
May 05 16:25:02 raspberrypi librespot[2360]:   15:   0x66e9f0 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::hd69ce85d2551a846
May 05 16:25:02 raspberrypi librespot[2360]:   16:   0x65f498 - <librespot_playback::player::PlayerInternal as core::future::future::Future>::poll::hf3f42b37b6d31e96
May 05 16:25:02 raspberrypi librespot[2360]:   17:   0x53067c - std::thread::local::LocalKey<T>::with::hfe703248c5b6b878
May 05 16:25:02 raspberrypi librespot[2360]:   18:   0x511914 - futures_executor::local_pool::block_on::h2606c989ae10467d
May 05 16:25:02 raspberrypi librespot[2360]:   19:   0x5badd4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d7d3e430e81e010
May 05 16:25:02 raspberrypi librespot[2360]:   20:   0x52784c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc36f91aa7ef2fc4b
May 05 16:25:02 raspberrypi librespot[2360]:   21:   0x964c6c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbc4d03a1815e028a
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
May 05 16:25:02 raspberrypi librespot[2360]:   22:   0x964c6c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6055603e421418e8
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
May 05 16:25:02 raspberrypi librespot[2360]:   23:   0x964c6c - std::sys::unix::thread::Thread::new::thread_start::h0518d9d0e6b0ba31
May 05 16:25:02 raspberrypi librespot[2360]:                        at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
```

**Comment by kirenida** [comment]
Solved - per issue https://github.com/librespot-org/librespot/issues/972 , playback works after blocking 'appresolve.spotify.com'
