### ISSUE TITLE
Librespot panics and fills syslog and daemon.log till SD capacity

### ISSUE THREAD

**Issue by pililac** [dtcooper/raspotify#609]
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

The both files /var/log/syslog and /var/log/daemon.log are filled till SD capacity is reached by librespot logs. Raspi stops working due to capacity limit reached.

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
pi@raspberry:~ $ sudo journalctl -u raspotify -b
Journal file /var/log/journal/4cc15c5c33bd417484c266a98199caf9/user-1000@0005f601c8747831-d5fce9b1e92d0ff3.journal~ is truncated, ignoring file.
-- Journal begins at Sat 2023-02-25 08:56:02 GMT, ends at Fri 2023-03-03 17:23:05 GMT. --
Feb 25 08:56:02 raspberry librespot[475]: 75668705:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668706:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668707:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668708:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668709:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668710:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668711:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668712:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668713:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668714:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668715:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668716:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668717:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668718:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668719:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668720:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668721:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668722:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668723:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668724:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668725:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668726:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668727:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668728:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668729:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668730:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668731:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668732:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668733:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668734:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668735:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668736:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668737:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668738:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668739:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668740:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668741:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668742:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668743:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668744:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668745:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668746:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668747:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668748:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668749:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668750:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668751:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668752:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668753:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668754:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668755:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668756:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668757:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668758:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668759:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668760:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668761:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668762:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668763:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668764:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668765:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668766:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668767:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668768:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668769:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668770:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668771:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668772:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668773:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668774:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668775:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668776:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668777:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668778:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668779:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52
Feb 25 08:56:24 raspberry librespot[475]: 75668780:       0x557167a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h45ae12a4d7295b52



pi@raspberry:~ $ sudo cat /etc/raspotify/crash_report
-- System Info --

Linux raspberry 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

-- Logs --

Feb 17 22:54:16 raspberry librespot[4289]: [2023-02-17T22:54:16Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:4070
Feb 17 22:54:16 raspberry librespot[4289]: [2023-02-17T22:54:16Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:443
Feb 17 22:54:16 raspberry librespot[4289]: [2023-02-17T22:54:16Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
Feb 17 22:54:16 raspberry librespot[4289]: [2023-02-17T22:54:16Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:80
Feb 17 22:54:16 raspberry librespot[4289]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: PathError { path: "/tmp/.tmpimGKVk", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', /mnt/raspotify/librespot/audio/src/fetch/mod.rs:365:51
Feb 17 22:54:16 raspberry librespot[4289]: stack backtrace:
Feb 17 22:54:16 raspberry librespot[4289]:    0:       0x559499c184 - std::backtrace_rs::backtrace::libunwind::trace::h4094424764928517
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
Feb 17 22:54:16 raspberry librespot[4289]:    1:       0x559499c184 - std::backtrace_rs::backtrace::trace_unsynchronized::h66a4d558a047d429
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Feb 17 22:54:16 raspberry librespot[4289]:    2:       0x559499c184 - std::sys_common::backtrace::_print_fmt::he501a9dfcbc65602
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
Feb 17 22:54:16 raspberry librespot[4289]:    3:       0x559499c184 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h500c865c023970a8
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
Feb 17 22:54:16 raspberry librespot[4289]:    4:       0x55947bc69c - core::fmt::write::h746b6837467f52c4
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
Feb 17 22:54:16 raspberry librespot[4289]:    5:       0x5594976af8 - std::io::Write::write_fmt::h9c3773c135795f84
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
Feb 17 22:54:16 raspberry librespot[4289]:    6:       0x559499ded4 - std::sys_common::backtrace::_print::haf80eda742d20a82
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
Feb 17 22:54:16 raspberry librespot[4289]:    7:       0x559499ded4 - std::sys_common::backtrace::print::h1af712ffba8f7735
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
Feb 17 22:54:16 raspberry librespot[4289]:    8:       0x559499db34 - std::panicking::default_hook::{{closure}}::hd82c56e3724f8bd8
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
Feb 17 22:54:16 raspberry librespot[4289]:    9:       0x559499ea40 - std::panicking::default_hook::h1f2a94f3a1c1c1aa
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
Feb 17 22:54:16 raspberry librespot[4289]:   10:       0x559499ea40 - std::panicking::rust_panic_with_hook::h01eb01a06bf17753
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
Feb 17 22:54:16 raspberry librespot[4289]:   11:       0x559499e58c - std::panicking::begin_panic_handler::{{closure}}::h657c9d34bb6d0855
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
Feb 17 22:54:16 raspberry librespot[4289]:   12:       0x559499e4fc - std::sys_common::backtrace::__rust_end_short_backtrace::h0b2d3ba55b6e5445
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
Feb 17 22:54:16 raspberry librespot[4289]:   13:       0x559499e4d8 - rust_begin_unwind
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
Feb 17 22:54:16 raspberry librespot[4289]:   14:       0x5594705ee8 - core::panicking::panic_fmt::h29641d0c529764f0
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
Feb 17 22:54:16 raspberry librespot[4289]:   15:       0x55947061b8 - core::result::unwrap_failed::h058c9a1e58c62fd7
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
Feb 17 22:54:16 raspberry librespot[4289]:   16:       0x559486c164 - librespot_playback::player::PlayerTrackLoader::load_track::{{closure}}::h7ccbba61bf17ba0d
Feb 17 22:54:16 raspberry librespot[4289]:   17:       0x5594865494 - std::sys_common::backtrace::__rust_begin_short_backtrace::hed192bbc3800d7a3
Feb 17 22:54:16 raspberry librespot[4289]:   18:       0x5594865298 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf4c21fcd5594e934
Feb 17 22:54:16 raspberry librespot[4289]:   19:       0x559499fdc4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h97d564fb54f53543
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
Feb 17 22:54:16 raspberry librespot[4289]:   20:       0x559499fdc4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd971138ad738ebef
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
Feb 17 22:54:16 raspberry librespot[4289]:   21:       0x559499fdc4 - std::sys::unix::thread::Thread::new::thread_start::h78f511bef4540085
Feb 17 22:54:16 raspberry librespot[4289]:                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
Feb 17 22:54:16 raspberry librespot[4289]:   22:       0x7f9a5c6648 - start_thread
Feb 17 22:54:16 raspberry librespot[4289]:                                at ./nptl/./nptl/pthread_create.c:477:8
Feb 17 22:54:17 raspberry librespot[4289]:   23:       0x7f9a45dc1c - thread_start
Feb 17 22:54:17 raspberry librespot[4289]:                                at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:78
Feb 17 22:54:17 raspberry librespot[4289]:   24:                0x0 - <unknown>
Feb 17 22:54:17 raspberry systemd[1]: raspotify.service: Main process exited, code=killed, status=6/ABRT
Feb 17 22:54:17 raspberry systemd[1]: raspotify.service: Failed with result 'signal'.
Feb 17 22:54:17 raspberry systemd[1]: raspotify.service: Triggering OnFailure= dependencies.

-- Config --

LIBRESPOT_QUIET=
LIBRESPOT_AUTOPLAY=
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=
LIBRESPOT_NAME="Stereoanlage Pirmin"
LIBRESPOT_BITRATE="160"
LIBRESPOT_FORMAT="S16"
LIBRESPOT_DEVICE_TYPE="avr"
LIBRESPOT_INITIAL_VOLUME="100"
LIBRESPOT_VOLUME_CTRL="linear"

-- Ouput of aplay -l --

**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

-- Ouput of aplay -L --

null
    Discard all samples (playback) or generate zero samples (capture)
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
hw:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Direct sample mixing device
hw:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi1
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi1
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Direct sample mixing device

-- Ouput of librespot -d ? --


        Compatible alsa device(s):

        ------------------------------------------------------

        Device:

                hw:CARD=Headphones,DEV=0

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Direct hardware device without any conversions

        Supported Format(s):

                S16

        ------------------------------------------------------

        Device:

                plughw:CARD=Headphones,DEV=0

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Hardware device with all software conversions

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                default:CARD=Headphones

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                sysdefault:CARD=Headphones

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                dmix:CARD=Headphones,DEV=0

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Direct sample mixing device

        Supported Format(s):

                S16

        ------------------------------------------------------
```

**Comment by pililac** [comment]
Sorry, it was NOT the newest version of raspotify, I'm using 0.43.29

````
pi@raspberry:~ $ apt show raspotify
Package: raspotify
Version: 0.43.29~librespot.v0.4.2-5cda505
Priority: optional
Section: base
Maintainer: Jason Gray <jasonlevigray3@gmail.com>
Installed-Size: 7,732 kB
Depends: libc6 (>= 2.31), coreutils (>= 8.32), libasound2 (>= 1.2.4), alsa-utils (>= 1.2.4), libpulse0 (>= 14.2), systemd (>= 247.3), init-system-helpers (>= 1.60)
Homepage: https://github.com/dtcooper/raspotify
Vcs-Browser: https://github.com/dtcooper/raspotify
Vcs-Git: https://github.com/dtcooper/raspotify
Download-Size: 1,674 kB
APT-Manual-Installed: yes
APT-Sources: https://dtcooper.github.io/raspotify raspotify/main arm64 Packages
Description: Raspotify
 A Spotify Connect systemd daemon for Debian Stable based headless systems which thinly wraps a fork of librespot.
 [Built with rustc 1.67.1]
````

**Comment by JasonLG1979** [comment]
Very strange? `/etc/raspotify/crash_report` mentions `/tmp/.tmpimGKVk` is not found. That possibly refers to a track that is supposed to cached to disk? After you clear the logs does the problem persist? `/etc/raspotify/crash_report` ***should*** capture the most recent relevant logs. I suppose if all else fails after a hard failure and log capture I could clear the logs?

**Comment by JasonLG1979** [comment]
Well never mind, my bad turns out you can't delete just one service's logs since the logs are interlaced. Kinda stupid design choice by systemd if you ask me...

**Comment by JasonLG1979** [comment]
The error seems to be coming from [this line](https://github.com/JasonLG1979/librespot/blob/raspotify/audio/src/fetch/mod.rs#L365) in the meantime until we figure out the cause I can make librespot cleanly exit with an error message and not puke a huge backtrace at least. Not ideal but better then what it's doing now.

**Comment by JasonLG1979** [comment]
@pililac I pushed this [commit](https://github.com/JasonLG1979/librespot/commit/b03804e4ceb4f75a27e81703575695270724c958) that causes librespot to exit more cleanly.

Can you test the latest Raspotify release?

**Comment by JasonLG1979** [comment]
I can not reproduce this bug. Closing this because of a lack of response.
